spring.application.name=FitnessApp
#Database connection prop
spring.datasource.url=jdbc:postgresql://localhost:5432/Fitness
spring.datasource.username=postgres
spring.datasource.password=postgres

#JPA prop
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

